import {shape} from './intf';
import {circle} from './circle';
import {square} from './square';
import {rectangle} from './rectangle';
 var cir :circle= new circle(7);
 var squ:square = new square(10);
 var rec: rectangle = new rectangle(10,12);
 console.log(cir.area());
 console.log(cir.draw());
 console.log(squ.area());
 console.log(squ.draw());
 console.log(rec.area());
 console.log(rec.draw());